// modules/emojiData.js
//
// Curated set of common emojis with keywords, used for ":name" autocomplete
// (e.g. :eye -> 👁). Only triggered by a leading colon, never bare words.
// Easy to extend; swap in a full Unicode dataset later if desired.

export const EMOJI = [
  // Smileys & emotion
  { char: '😀', name: 'grinning', keywords: ['smile', 'happy', 'face'] },
  { char: '😁', name: 'grin', keywords: ['smile', 'happy', 'teeth'] },
  { char: '😂', name: 'joy', keywords: ['laugh', 'cry', 'lol', 'tears'] },
  { char: '🤣', name: 'rofl', keywords: ['laugh', 'rolling', 'lmao'] },
  { char: '😃', name: 'smiley', keywords: ['happy', 'smile'] },
  { char: '😄', name: 'smile', keywords: ['happy', 'laugh'] },
  { char: '😅', name: 'sweat_smile', keywords: ['nervous', 'phew'] },
  { char: '😆', name: 'laughing', keywords: ['lol', 'haha'] },
  { char: '😉', name: 'wink', keywords: ['flirt', 'joke'] },
  { char: '😊', name: 'blush', keywords: ['happy', 'smile', 'shy'] },
  { char: '🙂', name: 'slight_smile', keywords: ['smile'] },
  { char: '🙃', name: 'upside_down', keywords: ['silly', 'sarcasm'] },
  { char: '😋', name: 'yum', keywords: ['tasty', 'tongue', 'delicious'] },
  { char: '😎', name: 'sunglasses', keywords: ['cool', 'shades'] },
  { char: '😍', name: 'heart_eyes', keywords: ['love', 'crush'] },
  { char: '😘', name: 'kissing_heart', keywords: ['kiss', 'love'] },
  { char: '🥰', name: 'smiling_hearts', keywords: ['love', 'adore'] },
  { char: '😗', name: 'kissing', keywords: ['kiss'] },
  { char: '🤩', name: 'star_struck', keywords: ['excited', 'wow', 'amazed'] },
  { char: '🤗', name: 'hug', keywords: ['hugging', 'embrace'] },
  { char: '🤔', name: 'thinking', keywords: ['hmm', 'consider'] },
  { char: '🤨', name: 'raised_eyebrow', keywords: ['skeptical', 'suspicious'] },
  { char: '😐', name: 'neutral', keywords: ['meh', 'blank'] },
  { char: '😑', name: 'expressionless', keywords: ['blank', 'meh'] },
  { char: '😶', name: 'no_mouth', keywords: ['silent', 'speechless'] },
  { char: '🙄', name: 'eye_roll', keywords: ['annoyed', 'whatever'] },
  { char: '😏', name: 'smirk', keywords: ['smug', 'sly'] },
  { char: '😣', name: 'persevere', keywords: ['struggle', 'ugh'] },
  { char: '😥', name: 'sad_relieved', keywords: ['disappointed', 'phew'] },
  { char: '😮', name: 'open_mouth', keywords: ['wow', 'surprise'] },
  { char: '🤐', name: 'zipper_mouth', keywords: ['quiet', 'secret'] },
  { char: '😯', name: 'hushed', keywords: ['surprise', 'wow'] },
  { char: '😪', name: 'sleepy', keywords: ['tired'] },
  { char: '😫', name: 'tired_face', keywords: ['exhausted', 'ugh'] },
  { char: '🥱', name: 'yawn', keywords: ['tired', 'bored'] },
  { char: '😴', name: 'sleeping', keywords: ['sleep', 'zzz'] },
  { char: '😌', name: 'relieved', keywords: ['calm', 'content'] },
  { char: '😛', name: 'tongue', keywords: ['playful', 'silly'] },
  { char: '😜', name: 'wink_tongue', keywords: ['joke', 'crazy'] },
  { char: '🤪', name: 'zany', keywords: ['crazy', 'goofy'] },
  { char: '😝', name: 'squint_tongue', keywords: ['silly', 'playful'] },
  { char: '🤑', name: 'money_mouth', keywords: ['rich', 'cash'] },
  { char: '🤓', name: 'nerd', keywords: ['geek', 'glasses'] },
  { char: '😒', name: 'unamused', keywords: ['annoyed', 'meh'] },
  { char: '😞', name: 'disappointed', keywords: ['sad'] },
  { char: '😔', name: 'pensive', keywords: ['sad', 'thoughtful'] },
  { char: '😕', name: 'confused', keywords: ['unsure'] },
  { char: '🙁', name: 'slight_frown', keywords: ['sad', 'frown'] },
  { char: '😖', name: 'confounded', keywords: ['frustrated'] },
  { char: '😟', name: 'worried', keywords: ['concern', 'nervous'] },
  { char: '😢', name: 'cry', keywords: ['sad', 'tear'] },
  { char: '😭', name: 'sob', keywords: ['cry', 'bawling', 'sad'] },
  { char: '😤', name: 'triumph', keywords: ['angry', 'huff'] },
  { char: '😠', name: 'angry', keywords: ['mad'] },
  { char: '😡', name: 'rage', keywords: ['mad', 'furious'] },
  { char: '🤬', name: 'cursing', keywords: ['swear', 'angry'] },
  { char: '😳', name: 'flushed', keywords: ['embarrassed', 'shock'] },
  { char: '🥵', name: 'hot_face', keywords: ['heat', 'sweaty'] },
  { char: '🥶', name: 'cold_face', keywords: ['freezing'] },
  { char: '😨', name: 'fearful', keywords: ['scared'] },
  { char: '😰', name: 'anxious', keywords: ['nervous', 'sweat'] },
  { char: '😱', name: 'scream', keywords: ['shock', 'fear'] },
  { char: '🤯', name: 'mind_blown', keywords: ['shocked', 'wow', 'explode'] },
  { char: '😬', name: 'grimace', keywords: ['awkward', 'yikes'] },
  { char: '😩', name: 'weary', keywords: ['tired', 'ugh'] },
  { char: '🥺', name: 'pleading', keywords: ['puppy', 'beg', 'cute'] },
  { char: '😇', name: 'innocent', keywords: ['angel', 'halo'] },
  { char: '🤠', name: 'cowboy', keywords: ['hat', 'yeehaw'] },
  { char: '🥳', name: 'partying', keywords: ['celebrate', 'party'] },
  { char: '😷', name: 'mask', keywords: ['sick', 'medical'] },
  { char: '🤒', name: 'thermometer_face', keywords: ['sick', 'ill'] },
  { char: '🤕', name: 'bandage_face', keywords: ['hurt', 'injured'] },
  { char: '🤢', name: 'nauseated', keywords: ['sick', 'gross'] },
  { char: '🤮', name: 'vomit', keywords: ['sick', 'puke'] },
  { char: '🤧', name: 'sneeze', keywords: ['sick', 'tissue'] },
  { char: '😈', name: 'smiling_imp', keywords: ['devil', 'evil'] },
  { char: '👿', name: 'imp', keywords: ['devil', 'angry'] },
  { char: '💀', name: 'skull', keywords: ['dead', 'death', 'lol'] },
  { char: '💩', name: 'poop', keywords: ['crap', 'poo'] },
  { char: '🤡', name: 'clown', keywords: ['joke', 'silly'] },
  { char: '👹', name: 'ogre', keywords: ['monster'] },
  { char: '👻', name: 'ghost', keywords: ['boo', 'spooky'] },
  { char: '👽', name: 'alien', keywords: ['ufo', 'space'] },
  { char: '🤖', name: 'robot', keywords: ['bot', 'ai'] },
  { char: '😺', name: 'cat_smile', keywords: ['kitty'] },
  { char: '😻', name: 'cat_heart_eyes', keywords: ['love', 'kitty'] },

  // Gestures & body
  { char: '👍', name: 'thumbsup', keywords: ['like', 'yes', 'approve', '+1'] },
  { char: '👎', name: 'thumbsdown', keywords: ['dislike', 'no', '-1'] },
  { char: '👌', name: 'ok_hand', keywords: ['perfect', 'okay'] },
  { char: '🤌', name: 'pinched_fingers', keywords: ['italian', 'chef'] },
  { char: '✌️', name: 'peace', keywords: ['victory', 'two'] },
  { char: '🤞', name: 'fingers_crossed', keywords: ['luck', 'hope'] },
  { char: '🤟', name: 'love_you_gesture', keywords: ['ily'] },
  { char: '🤘', name: 'rock_on', keywords: ['metal', 'horns'] },
  { char: '🤙', name: 'call_me', keywords: ['shaka', 'hang loose'] },
  { char: '👈', name: 'point_left', keywords: ['left'] },
  { char: '👉', name: 'point_right', keywords: ['right'] },
  { char: '👆', name: 'point_up', keywords: ['up'] },
  { char: '👇', name: 'point_down', keywords: ['down'] },
  { char: '☝️', name: 'index_up', keywords: ['one', 'up'] },
  { char: '✋', name: 'raised_hand', keywords: ['stop', 'high five'] },
  { char: '🤚', name: 'back_hand', keywords: ['stop'] },
  { char: '🖐️', name: 'hand_splayed', keywords: ['five', 'stop'] },
  { char: '🖖', name: 'vulcan', keywords: ['spock', 'star trek'] },
  { char: '👋', name: 'wave', keywords: ['hello', 'hi', 'bye'] },
  { char: '🤝', name: 'handshake', keywords: ['deal', 'agree'] },
  { char: '👏', name: 'clap', keywords: ['applause', 'bravo'] },
  { char: '🙌', name: 'raised_hands', keywords: ['praise', 'celebrate'] },
  { char: '👐', name: 'open_hands', keywords: ['hug'] },
  { char: '🙏', name: 'pray', keywords: ['please', 'thanks', 'thank you', 'hope'] },
  { char: '✍️', name: 'writing', keywords: ['write'] },
  { char: '💪', name: 'muscle', keywords: ['strong', 'flex', 'gym'] },
  { char: '🦾', name: 'mechanical_arm', keywords: ['strong', 'robot'] },
  { char: '👀', name: 'eyes', keywords: ['look', 'watch', 'see'] },
  { char: '👁️', name: 'eye', keywords: ['look', 'see'] },
  { char: '🫶', name: 'heart_hands', keywords: ['love', 'thanks'] },
  { char: '🫡', name: 'salute', keywords: ['respect', 'yes sir'] },
  { char: '🤷', name: 'shrug', keywords: ['idk', 'whatever'] },
  { char: '🤦', name: 'facepalm', keywords: ['smh', 'ugh'] },
  { char: '🧠', name: 'brain', keywords: ['smart', 'mind'] },

  // Hearts & symbols of emotion
  { char: '❤️', name: 'heart', keywords: ['love', 'red'] },
  { char: '🧡', name: 'orange_heart', keywords: ['love'] },
  { char: '💛', name: 'yellow_heart', keywords: ['love'] },
  { char: '💚', name: 'green_heart', keywords: ['love'] },
  { char: '💙', name: 'blue_heart', keywords: ['love'] },
  { char: '💜', name: 'purple_heart', keywords: ['love'] },
  { char: '🖤', name: 'black_heart', keywords: ['love'] },
  { char: '🤍', name: 'white_heart', keywords: ['love'] },
  { char: '💔', name: 'broken_heart', keywords: ['sad', 'heartbreak'] },
  { char: '💕', name: 'two_hearts', keywords: ['love'] },
  { char: '💖', name: 'sparkling_heart', keywords: ['love'] },
  { char: '💘', name: 'cupid', keywords: ['love', 'arrow'] },
  { char: '💯', name: '100', keywords: ['hundred', 'perfect', 'keep it real'] },
  { char: '💢', name: 'anger', keywords: ['mad', 'comic'] },
  { char: '💥', name: 'boom', keywords: ['explosion', 'collision'] },
  { char: '💫', name: 'dizzy', keywords: ['stars', 'sparkle'] },
  { char: '💦', name: 'sweat_drops', keywords: ['water', 'splash'] },
  { char: '💨', name: 'dash', keywords: ['fast', 'wind'] },
  { char: '🔥', name: 'fire', keywords: ['lit', 'hot', 'flame'] },
  { char: '✨', name: 'sparkles', keywords: ['shiny', 'clean', 'magic'] },
  { char: '⭐', name: 'star', keywords: ['favorite'] },
  { char: '🌟', name: 'star2', keywords: ['glowing', 'shine'] },
  { char: '⚡', name: 'zap', keywords: ['lightning', 'fast', 'power'] },
  { char: '☀️', name: 'sunny', keywords: ['sun', 'weather'] },
  { char: '🌈', name: 'rainbow', keywords: ['pride', 'colors'] },

  // Animals
  { char: '🐶', name: 'dog', keywords: ['puppy', 'pet'] },
  { char: '🐱', name: 'cat', keywords: ['kitty', 'pet'] },
  { char: '🐭', name: 'mouse', keywords: ['rodent'] },
  { char: '🐹', name: 'hamster', keywords: ['pet'] },
  { char: '🐰', name: 'rabbit', keywords: ['bunny'] },
  { char: '🦊', name: 'fox', keywords: ['animal'] },
  { char: '🐻', name: 'bear', keywords: ['animal'] },
  { char: '🐼', name: 'panda', keywords: ['bear'] },
  { char: '🐨', name: 'koala', keywords: ['animal'] },
  { char: '🐯', name: 'tiger', keywords: ['cat'] },
  { char: '🦁', name: 'lion', keywords: ['cat'] },
  { char: '🐮', name: 'cow', keywords: ['moo'] },
  { char: '🐷', name: 'pig', keywords: ['oink'] },
  { char: '🐸', name: 'frog', keywords: ['toad'] },
  { char: '🐵', name: 'monkey_face', keywords: ['ape'] },
  { char: '🐔', name: 'chicken', keywords: ['hen'] },
  { char: '🐧', name: 'penguin', keywords: ['bird'] },
  { char: '🐦', name: 'bird', keywords: ['tweet'] },
  { char: '🦆', name: 'duck', keywords: ['quack'] },
  { char: '🦅', name: 'eagle', keywords: ['bird'] },
  { char: '🦉', name: 'owl', keywords: ['bird', 'hoot'] },
  { char: '🐺', name: 'wolf', keywords: ['animal'] },
  { char: '🐗', name: 'boar', keywords: ['pig'] },
  { char: '🐴', name: 'horse_face', keywords: ['pony'] },
  { char: '🦄', name: 'unicorn', keywords: ['magic'] },
  { char: '🐝', name: 'bee', keywords: ['honey', 'buzz'] },
  { char: '🐛', name: 'bug', keywords: ['insect'] },
  { char: '🦋', name: 'butterfly', keywords: ['insect'] },
  { char: '🐌', name: 'snail', keywords: ['slow'] },
  { char: '🐢', name: 'turtle', keywords: ['slow'] },
  { char: '🐍', name: 'snake', keywords: ['reptile'] },
  { char: '🐙', name: 'octopus', keywords: ['sea'] },
  { char: '🐠', name: 'fish', keywords: ['sea'] },
  { char: '🐬', name: 'dolphin', keywords: ['sea'] },
  { char: '🐳', name: 'whale', keywords: ['sea'] },
  { char: '🦈', name: 'shark', keywords: ['sea'] },
  { char: '🐊', name: 'crocodile', keywords: ['gator'] },

  // Food & drink
  { char: '🍎', name: 'apple', keywords: ['fruit', 'red'] },
  { char: '🍌', name: 'banana', keywords: ['fruit'] },
  { char: '🍓', name: 'strawberry', keywords: ['fruit'] },
  { char: '🍒', name: 'cherries', keywords: ['fruit'] },
  { char: '🍑', name: 'peach', keywords: ['fruit', 'butt'] },
  { char: '🍉', name: 'watermelon', keywords: ['fruit'] },
  { char: '🍊', name: 'orange', keywords: ['fruit'] },
  { char: '🍍', name: 'pineapple', keywords: ['fruit'] },
  { char: '🥑', name: 'avocado', keywords: ['guac'] },
  { char: '🍆', name: 'eggplant', keywords: ['veg'] },
  { char: '🌽', name: 'corn', keywords: ['veg'] },
  { char: '🌶️', name: 'hot_pepper', keywords: ['spicy', 'chili'] },
  { char: '🍕', name: 'pizza', keywords: ['food', 'slice'] },
  { char: '🍔', name: 'burger', keywords: ['food', 'hamburger'] },
  { char: '🍟', name: 'fries', keywords: ['food', 'chips'] },
  { char: '🌭', name: 'hotdog', keywords: ['food'] },
  { char: '🌮', name: 'taco', keywords: ['food', 'mexican'] },
  { char: '🌯', name: 'burrito', keywords: ['food'] },
  { char: '🍗', name: 'poultry_leg', keywords: ['chicken', 'food'] },
  { char: '🍿', name: 'popcorn', keywords: ['movie', 'snack'] },
  { char: '🍩', name: 'donut', keywords: ['sweet'] },
  { char: '🍪', name: 'cookie', keywords: ['sweet'] },
  { char: '🎂', name: 'cake', keywords: ['birthday', 'dessert'] },
  { char: '🍰', name: 'shortcake', keywords: ['cake', 'dessert'] },
  { char: '🍫', name: 'chocolate', keywords: ['sweet'] },
  { char: '🍬', name: 'candy', keywords: ['sweet'] },
  { char: '🍭', name: 'lollipop', keywords: ['sweet'] },
  { char: '🍦', name: 'icecream', keywords: ['dessert', 'sweet'] },
  { char: '☕', name: 'coffee', keywords: ['drink', 'tea'] },
  { char: '🍵', name: 'tea', keywords: ['drink'] },
  { char: '🍺', name: 'beer', keywords: ['drink', 'alcohol'] },
  { char: '🍻', name: 'beers', keywords: ['cheers', 'drink'] },
  { char: '🍷', name: 'wine', keywords: ['drink', 'alcohol'] },
  { char: '🥂', name: 'champagne', keywords: ['cheers', 'celebrate'] },
  { char: '🍸', name: 'cocktail', keywords: ['drink'] },

  // Activities & travel
  { char: '⚽', name: 'soccer', keywords: ['football', 'ball'] },
  { char: '🏀', name: 'basketball', keywords: ['ball'] },
  { char: '🏈', name: 'football', keywords: ['ball', 'nfl'] },
  { char: '⚾', name: 'baseball', keywords: ['ball'] },
  { char: '🎾', name: 'tennis', keywords: ['ball'] },
  { char: '🎮', name: 'video_game', keywords: ['gaming', 'controller'] },
  { char: '🎯', name: 'dart', keywords: ['target', 'bullseye'] },
  { char: '🎲', name: 'dice', keywords: ['game', 'random'] },
  { char: '🎵', name: 'musical_note', keywords: ['music', 'song'] },
  { char: '🎶', name: 'notes', keywords: ['music', 'song'] },
  { char: '🎤', name: 'microphone', keywords: ['sing', 'mic'] },
  { char: '🎧', name: 'headphones', keywords: ['music', 'audio'] },
  { char: '🎸', name: 'guitar', keywords: ['music'] },
  { char: '🎉', name: 'tada', keywords: ['party', 'celebrate', 'congrats'] },
  { char: '🎊', name: 'confetti', keywords: ['party', 'celebrate'] },
  { char: '🎁', name: 'gift', keywords: ['present', 'birthday'] },
  { char: '🚀', name: 'rocket', keywords: ['space', 'launch', 'fast'] },
  { char: '🚗', name: 'car', keywords: ['vehicle', 'drive'] },
  { char: '✈️', name: 'airplane', keywords: ['flight', 'travel'] },
  { char: '🏠', name: 'house', keywords: ['home'] },
  { char: '🌍', name: 'earth', keywords: ['world', 'globe'] },
  { char: '🌙', name: 'moon', keywords: ['night'] },

  // Objects & symbols
  { char: '💡', name: 'bulb', keywords: ['idea', 'light'] },
  { char: '🔑', name: 'key', keywords: ['lock', 'unlock'] },
  { char: '🔒', name: 'lock', keywords: ['secure', 'closed'] },
  { char: '📱', name: 'phone', keywords: ['mobile', 'cell'] },
  { char: '💻', name: 'laptop', keywords: ['computer'] },
  { char: '⌨️', name: 'keyboard', keywords: ['type'] },
  { char: '🖥️', name: 'desktop', keywords: ['computer', 'pc'] },
  { char: '📷', name: 'camera', keywords: ['photo'] },
  { char: '🎥', name: 'movie_camera', keywords: ['film', 'video'] },
  { char: '📺', name: 'tv', keywords: ['television'] },
  { char: '💰', name: 'moneybag', keywords: ['cash', 'rich'] },
  { char: '💵', name: 'dollar', keywords: ['money', 'cash'] },
  { char: '💎', name: 'gem', keywords: ['diamond', 'jewel'] },
  { char: '🏆', name: 'trophy', keywords: ['win', 'award'] },
  { char: '🥇', name: 'first_place', keywords: ['gold', 'medal', 'win'] },
  { char: '🎖️', name: 'medal', keywords: ['award', 'honor'] },
  { char: '🔔', name: 'bell', keywords: ['notification', 'alert'] },
  { char: '📣', name: 'megaphone', keywords: ['announce', 'shout'] },
  { char: '✅', name: 'check', keywords: ['done', 'yes', 'correct'] },
  { char: '❌', name: 'x', keywords: ['no', 'cross', 'wrong'] },
  { char: '❗', name: 'exclamation', keywords: ['warning', 'important'] },
  { char: '❓', name: 'question', keywords: ['help', 'huh'] },
  { char: '⚠️', name: 'warning', keywords: ['caution', 'alert'] },
  { char: '🚫', name: 'no_entry', keywords: ['banned', 'prohibited'] },
  { char: '♻️', name: 'recycle', keywords: ['green', 'reuse'] },
  { char: '➡️', name: 'arrow_right', keywords: ['next'] },
  { char: '⬅️', name: 'arrow_left', keywords: ['back'] },
  { char: '⬆️', name: 'arrow_up', keywords: ['up'] },
  { char: '⬇️', name: 'arrow_down', keywords: ['down'] },
  { char: '🔁', name: 'repeat', keywords: ['loop'] },
  { char: '▶️', name: 'play', keywords: ['start'] },
  { char: '⏸️', name: 'pause', keywords: ['stop'] },
];

// Search emojis by name/keyword for ":colon" autocomplete. Prefix matches rank
// above substring matches. Returns autocomplete-shaped candidates.
export function searchEmoji(query, limit = 20) {
  const q = String(query || '').toLowerCase();
  if (!q) return [];
  const starts = [];
  const includes = [];
  for (const emoji of EMOJI) {
    const name = emoji.name.toLowerCase();
    if (name.startsWith(q) || emoji.keywords.some(k => k.startsWith(q))) {
      starts.push(emoji);
    } else if (name.includes(q) || emoji.keywords.some(k => k.includes(q))) {
      includes.push(emoji);
    }
  }
  return [...starts, ...includes]
    .slice(0, limit)
    .map(emoji => ({ name: emoji.name, char: emoji.char, isEmoji: true }));
}
